import { expect, test, type Route } from '@playwright/test'
import { createLearnerAndLogin } from './helpers/registerLearner'

test('题目 AI 可停止后重试，资产读取失败和反馈失败均可原位恢复', async ({ page, browser }, testInfo) => {
  test.setTimeout(90_000)
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await createLearnerAndLogin(browser, page, 'ai-learning')
  await page.goto('/questions?questionId=1')
  await page.getByRole('button', { name: '练这道题', exact: true }).click()
  await page.getByRole('radio', { name: 'B. implements', exact: true }).check()
  await page.getByRole('button', { name: '提交答案', exact: true }).click()
  await page.getByText('继续理解这道题', { exact: true }).click()
  const assistant = page.getByRole('region', { name: 'AI 学习助手', exact: true })

  let release!: (route: Route) => void
  const held = new Promise<Route>((resolve) => (release = resolve))
  await page.route('**/ai/explanation/stream', (route) => release(route), { times: 1 })
  await assistant.getByRole('button', { name: '补充解析', exact: true }).click()
  const pausedRoute = await held
  await assistant.getByRole('button', { name: '停止生成', exact: true }).click()
  await expect(assistant).toContainText('已停止，当前内容可能不完整。')
  await pausedRoute.abort().catch(() => undefined)
  const generated = page.waitForResponse((response) => response.url().endsWith('/ai/explanation/stream'))
  await assistant.getByRole('button', { name: '重新生成', exact: true }).click()
  expect((await generated).status()).toBe(200)
  await expect(assistant.getByText('AI 生成', { exact: true })).toBeVisible()
  await expect(assistant.getByRole('button', { name: '停止生成' })).toHaveCount(0)
  await expect(assistant.locator('.markdown-body')).not.toBeEmpty()

  await page.route('**/ai/assets/1', (route) => route.abort(), { times: 1 })
  const assets = page.getByRole('region', { name: 'AI 深度学习', exact: true })
  await assets.getByRole('button', { name: 'AI 深度学习', exact: true }).click()
  await expect(assets).toContainText('已有讲解暂时无法读取')
  await assets.getByRole('button', { name: '重试', exact: true }).click()
  await expect(assets.getByText('已有讲解暂时无法读取', { exact: false })).toHaveCount(0)
  const generate = assets.getByRole('button', { name: '生成标准解析', exact: true })
  await expect(assets.locator('.asset-content')).toBeVisible()
  if (await generate.isVisible()) await generate.click()
  const feedback = assets.locator('.feedback-area')
  await expect(feedback).toBeVisible()
  await expect(feedback.getByText('正在读取反馈…', { exact: true })).toHaveCount(0)
  const revise = feedback.getByRole('button', { name: '重新反馈', exact: true })
  if (await revise.isVisible()) await revise.click()
  await page.route('**/ai/asset/feedback', (route) => route.abort(), { times: 1 })
  await feedback.getByRole('button', { name: '没帮助', exact: true }).click()
  await expect(feedback).toContainText('提交反馈失败，请重试。')
  await feedback.getByRole('button', { name: '重试', exact: true }).click()
  await expect(feedback).toContainText('已反馈：没帮助')
  await expect(feedback.getByRole('alert')).toHaveCount(0)
  await expect(page.locator('.el-message--error')).toHaveCount(0)
  await assets.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('ai-learning-recovered.png') })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
