-- DualArrayDeque 模块首个切片：双栈表示与逻辑下标映射，不延伸至按位更新、再平衡或复杂度。
INSERT INTO knowledge_point (name, description, course_id, parent_id, content_key, content_source, content_version, content_review_status, sort_order, deleted)
SELECT 'DualArrayDeque 的双栈表示', 'front 逆序保存逻辑前缀，back 正序保存逻辑后缀；逻辑序列为 reverse(front) 后接 back。', course.id, parent.id, 'ods-dualarraydeque-representation', 'AISTU', 1, 'REVIEWED', 24, 0
FROM course JOIN knowledge_point parent ON parent.course_id = course.id AND parent.content_key = '408-stacks-queues-arrays' LEFT JOIN knowledge_point existing ON existing.content_key = 'ods-dualarraydeque-representation'
WHERE course.content_key = 'cs408-data-structures' AND existing.id IS NULL;
INSERT INTO tutor_content (knowledge_point_id, content_key, content_version, review_status, title, lesson_json, check_json)
SELECT point.id, 'ods-dualarraydeque-representation', 1, 'REVIEWED', 'DualArrayDeque 的双栈表示',
JSON_OBJECT('summary', 'DualArrayDeque 用两个 ArrayStack 表示一个 List：front 逆序保存逻辑前缀，back 正序保存逻辑后缀。逻辑下标 i 小于 front.size() 时映射到 front[front.size()-i-1]，否则映射到 back[i-front.size()]。', 'steps', JSON_ARRAY('front 与 back 的元素总数构成逻辑 List 长度 n', '读取逻辑序列时先反向读取 front，再正向读取 back', 'i < front.size() 时用反向下标访问 front', '否则用 i-front.size() 访问 back'), 'visualization', JSON_OBJECT('kind', 'DUAL_ARRAY_DEQUE_REPRESENTATION', 'version', 1, 'front', JSON_ARRAY('B', 'A'), 'back', JSON_ARRAY('C', 'D', 'E'), 'accessIndex', 1), 'prerequisite', JSON_OBJECT('contentKey', 'ods-arraydeque-representation', 'title', 'ArrayDeque 的循环数组表示', 'description', '先理解逻辑顺序与内部存储顺序可以不同。'), 'nextStep', JSON_OBJECT('contentKey', 'ods-dualarraydeque-end-operations', 'title', 'DualArrayDeque 的按位更新', 'description', '继续学习如何把按位操作路由到正确的内部栈。')),
JSON_OBJECT('id', 'dualarraydeque-front-reverse-v1', 'prompt', 'front 从栈底到栈顶为 B、A，back 从栈底到栈顶为 C、D、E。逻辑 List 的顺序是什么？', 'options', JSON_ARRAY(JSON_OBJECT('id', 'FRONT_REVERSE', 'text', 'A、B、C、D、E：front 需要反向读取，再接 back'), JSON_OBJECT('id', 'STACK_ORDER', 'text', 'B、A、C、D、E：两个栈都按保存顺序直接连接')), 'correctOptionId', 'FRONT_REVERSE', 'correctExplanation', '正确：front 保存逻辑前缀的逆序，因此读取逻辑序列时要先反转 front，再接上正序 back。', 'incorrectExplanation', '不正确：直接连接会把逻辑前缀反过来。front 的逆序布局是为了让逻辑前端靠近其栈顶。')
FROM knowledge_point point LEFT JOIN tutor_content existing ON existing.content_key = 'ods-dualarraydeque-representation' AND existing.content_version = 1
WHERE point.content_key = 'ods-dualarraydeque-representation' AND existing.id IS NULL;
